source 'http://rubygems.org'

gem 'rails', '3.1'

gem 'sqlite3'

gem 'nokogiri'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'pg'
gem 'haml'
gem 'sass'
gem 'sass-rails'
gem 'heroku'
gem 'heroku_san', '<= 2.0.0'
gem 'jquery-rails'
gem 'formtastic'
gem 'devise', '1.4.7'
gem 'paper_trail'
gem 'dalli'
gem 'paperclip'
gem 'validate_url'
gem 'aws-s3'
gem 'mechanize'
gem 'delayed_job'
gem 'aws-sdk'
gem 'twitter-bootstrap-rails'
gem 'formtastic-bootstrap', :git => 'git://github.com/cgunther/formtastic-bootstrap.git', :branch => 'bootstrap-2'
gem 'bootstrap-sass-rails'
gem 'uglifier'
gem 'on_the_spot'
gem 'statsd-instrument'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'gherkin'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails'
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem 'autotest-rails'
  gem 'test_notifier'
  gem 'awesome_print'
  gem 'machinist'
  gem 'faker'
  gem 'ruby-debug19'
  gem 'bermuda'
  gem 'blueprints'
  gem 'fakeweb'
  gem 'silent-postgres'
  gem 'capybara-webkit', '0.8.0'

  gem 'bullet'
  gem 'roodi', :git => 'git://github.com/Jetstar/roodi.git'
  gem 'rcov', '0.9.11'
  gem 'metric_fu'
  gem 'fattr'
  gem 'arrayfields'
  gem 'map'
  gem 'jslint_on_rails'
  gem 'cucumber_timing_presenter'

  gem 'magic_encoding'
end
