#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
prod: 
  app: pushflashbang
  config:
    BUNDLE_WITHOUT: "development:test"
#    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  app: pushflashbang-preprod
  config: &default
    BUNDLE_WITHOUT: "development:test"

demo: 
  app: pushflashbang-demo
  config: *default
