development:
  bucket: pushflashbang-dev
  access_key_id: AKIAISK27CHO6F5NPLWQ
  secret_access_key: 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
test:
  bucket: pushflashbang-dev
  access_key_id: AKIAISK27CHO6F5NPLWQ
  secret_access_key: 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
production:
  bucket: pushflashbang
  access_key_id: AKIAISK27CHO6F5NPLWQ
  secret_access_key: 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