def add_cards_to_forward_deck deck, cards
  cards.each do |card|
    next if card["new"].nil?
    next if card["new"] == "no"

    exists = Card.where(:front => card["front"], :deck_id => deck.id)

    if card["new"] == "yes"
      unless exists.empty?
        raise "card #{card["front"]} already exists in deck #{deck["name"]}"
      end

      card = Card.new(:front => card["front"], :back => card["back"], :pronunciation => card["pronunciation"], :chapter => card["chapter"])
      card.deck = deck
      card.save!

      puts "#{card["front"]} created in deck #{deck["name"]}"
    elsif card["new"] == "update"
      if exists.empty?
        raise "trying to update card  #{card["front"]} that does not exist in deck #{deck["name"]}"
      end

      exists.first.back = card["back"]
      exists.first.pronunciation = card["pronunciation"]
      exists.first.chapter = card["chapter"]
      exists.first.save!

      puts "#{card["front"]} updated in deck #{deck["name"]}"
    end
  end
end

def add_cards_to_reverse_deck deck, cards
  cards.each do |card|
    next if card["new"].nil?
    next if card["new"] == "no"

    exists = Card.where(:front => card["back"], :deck_id => deck.id)

    if card["new"] == "yes"
      unless exists.empty?
        raise "card #{card["back"]} already exists in deck #{deck["name"]}"
      end

      card = Card.new(:front => card["back"], :back => card["front"], :pronunciation => card["pronunciation"], :chapter => card["chapter"])
      card.deck = deck
      card.save!

      puts "#{card["back"]} created in deck #{deck["name"]}"
    elsif card["new"] == "update"
      if exists.empty?
        raise "trying to update card  #{card["back"]} that does not exist in deck #{deck["name"]}"
      end

      exists.first.back = card["front"]
      exists.first.pronunciation = card["pronunciation"]
      exists.first.chapter = card["chapter"]
      exists.first.save!

      puts "#{card["back"]} updated in deck #{deck["name"]}"
    end
  end
end

unless CardTiming.count > 0
  CardTiming.create(:seconds => 5)                                       # 5 seconds
  CardTiming.create(:seconds => 25)                                      # 25 seconds
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_MINUTE * 2)        # 2 minutes
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_MINUTE * 10)       # 10 minutes
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_HOUR)              # 1 hour
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_HOUR * 5)          # 5 hours
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_DAY)               # 1 day
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_DAY * 5)           # 5 days
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_DAY * 25)          # 25 days
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_MONTH * 4)         # 4 months
  CardTiming.create(:seconds => CardTiming::SECONDS_IN_YEAR * 2)          # 2 years
end


user = User.where(:email => 'ryan.boucher@distributedlife.com')
if user.empty?
  user = User.create(:email => 'ryan.boucher@distributedlife.com', :password => 'FSG2342edkj!', :confrim_password => 'FSG2342edkj!')
else
  user = user.first
end

def get_or_create_deck name, user_id, shared, supports_written_answer, pronunciation_side
  deck = Deck.where(:name => name, :user_id => user_id)

  if deck.empty?
    deck = Deck.new(:name => name, :shared => shared, :supports_written_answer => supports_written_answer, :pronunciation_side => pronunciation_side)
    deck.user = user
    deck.save!

    puts "created deck #{name}"
  else
    deck = deck.first

    puts "found deck #{name}"
  end

  deck
end

forward_deck = get_or_create_deck 'Simplified Hanzi to English (reading)', user.id, true, false, 'front'
reverse_deck = get_or_create_deck 'English to Simplified Hanzi (writing)', user.id, true, false, 'front'


cards = []
cards = [
  #Lesson 1
  {"front" => "一", "back" => "1 / (floor, ceiling)", "chapter" => "1", "new" => "no"},
  {"front" => "二", "back" => "2", "chapter" => "1", "new" => "no"},
  {"front" => "三", "back" => "3", "chapter" => "1", "new" => "no"},
  {"front" => "四", "back" => "4", "chapter" => "1", "new" => "no"},
  {"front" => "五", "back" => "5", "chapter" => "1", "new" => "no"},
  {"front" => "六", "back" => "6", "chapter" => "1", "new" => "no"},
  {"front" => "七", "back" => "7 / (diced)", "chapter" => "1", "new" => "no"},
  {"front" => "八", "back" => "8", "chapter" => "1", "new" => "no"},
  {"front" => "九", "back" => "9 / (baseball)", "chapter" => "1", "new" => "no"},
  {"front" => "十", "back" => "10", "chapter" => "1", "new" => "no"},
  {"front" => "目", "back" => "eye", "chapter" => "1", "new" => "no"},
  {"front" => "月", "back" => "month / (moon, flesh, part of body)", "chapter" => "1", "new" => "no"},
  {"front" => "口", "back" => "mouth", "chapter" => "1", "new" => "no"},
  {"front" => "田", "back" => "rice field / (brains)", "chapter" => "1", "new" => "no"},
  {"front" => "日", "back" => "day / (sun, tonque wagging)", "chapter" => "1", "new" => "no"},
  #Lesson 2
  {"front" => "古", "back" => "ancient", "chapter" => "2", "new" => "no"},
  {"front" => "胡", "back" => "recklessly", "chapter" => "2", "new" => "no"},
  {"front" => "叶", "back" => "leaf", "chapter" => "2", "new" => "no"},
  {"front" => "吾", "back" => "I (literary)", "chapter" => "2", "new" => "no"},
  {"front" => "朋", "back" => "companion", "chapter" => "2", "new" => "no"},
  {"front" => "明", "back" => "bright", "chapter" => "2", "new" => "no"},
  {"front" => "唱", "back" => "sing", "chapter" => "2", "new" => "no"},
  {"front" => "晶", "back" => "sparkling", "chapter" => "2", "new" => "no"},
  {"front" => "品", "back" => "goods", "chapter" => "2", "new" => "no"},
  {"front" => "昌", "back" => "prosperous", "chapter" => "2", "new" => "no"},
  {"front" => "早", "back" => "early / (sunflower)", "chapter" => "2", "new" => "no"},
  {"front" => "旭", "back" => "rising sun", "chapter" => "2", "new" => "no"},
  {"front" => "世", "back" => "generation", "chapter" => "2", "new" => "no"},
  {"front" => "胃", "back" => "stomach", "chapter" => "2", "new" => "no"},
  {"front" => "旦", "back" => "daybreak", "chapter" => "2", "new" => "no"},
  {"front" => "凹", "back" => "concave", "chapter" => "2", "new" => "no"},
  {"front" => "凸", "back" => "convex", "chapter" => "2", "new" => "no"},
  #Lesson 3
  {"front" => "自", "back" => "oneself / (nose)", "chapter" => "3", "new" => "no"},
  {"front" => "白", "back" => "white", "chapter" => "3", "new" => "no"},
  {"front" => "百", "back" => "hundred", "chapter" => "3", "new" => "no"},
  {"front" => "皂", "back" => "soap", "chapter" => "3", "new" => "no"},
  {"front" => "旧", "back" => "old", "chapter" => "3", "new" => "no"},
  {"front" => "中", "back" => "middle [n/adj]", "chapter" => "3", "new" => "no"},
  {"front" => "千", "back" => "thousand", "chapter" => "3", "new" => "no"},
  {"front" => "舌", "back" => "tonque", "chapter" => "3", "new" => "no"},
  {"front" => "升", "back" => "litre", "chapter" => "3", "new" => "no"},
  {"front" => "丸", "back" => "pill / (bottle of pills)", "chapter" => "3", "new" => "no"},
  {"front" => "卜", "back" => "divination / (divining rod / magic wand)", "chapter" => "3", "new" => "no"},
  {"front" => "占", "back" => "tell fortunes", "chapter" => "3", "new" => "no"},
  {"front" => "上", "back" => "above", "chapter" => "3", "new" => "no"},
  {"front" => "下", "back" => "below", "chapter" => "3", "new" => "no"},
  {"front" => "卡", "back" => "card", "chapter" => "3", "new" => "no"},
  {"front" => "卓", "back" => "eminent", "chapter" => "3", "new" => "no"},
  {"front" => "朝", "back" => "dynasty", "chapter" => "3", "new" => "no"},
  {"front" => "嘲", "back" => "ridicule [v]", "chapter" => "3", "new" => "no"},
  #Lesson 4
  {"front" => "只", "back" => "only", "chapter" => "4", "new" => "no"},
  {"front" => "贝", "back" => "shellfish", "chapter" => "4", "new" => "no"},
  {"front" => "贴", "back" => "paste [v]", "chapter" => "4", "new" => "no"},
  {"front" => "贞", "back" => "chaste", "chapter" => "4", "new" => "no"},
  {"front" => "员", "back" => "employee", "chapter" => "4", "new" => "no"},
  {"front" => "儿", "back" => "youngster / (human legs)", "chapter" => "4", "new" => "no"},
  {"front" => "几", "back" => "how many? / (wind / small table)", "chapter" => "4", "new" => "no"},
  {"front" => "见", "back" => "see", "chapter" => "4", "new" => "no"},
  {"front" => "元", "back" => "beginning", "chapter" => "4", "new" => "no"},
  {"front" => "页", "back" => "page / (head)", "chapter" => "4", "new" => "no"},
  {"front" => "顽", "back" => "stubborn", "chapter" => "4", "new" => "no"},
  {"front" => "凡", "back" => "ordinary", "chapter" => "4", "new" => "no"},
  {"front" => "肌", "back" => "muscle", "chapter" => "4", "new" => "no"},
  {"front" => "负", "back" => "defeated [adj]", "chapter" => "4", "new" => "no"},
  {"front" => "万", "back" => "ten thousand", "chapter" => "4", "new" => "no"},
  {"front" => "匀", "back" => "uniform [adj]", "chapter" => "4", "new" => "no"},
  {"front" => "句", "back" => "sentence [n]", "chapter" => "4", "new" => "no"},
  {"front" => "旬", "back" => "decameron", "chapter" => "4", "new" => "no"},
  {"front" => "勺", "back" => "ladle", "chapter" => "4", "new" => "no"},
  {"front" => "的", "back" => "bull's eye", "chapter" => "4", "new" => "no"},
  {"front" => "首", "back" => "heads", "chapter" => "4", "new" => "no"},

  #Lesson 5
  {"front" => "直", "back" => "straight", "chapter" => "5", "new" => "no"},
  {"front" => "置", "back" => "setup", "chapter" => "5", "new" => "no"},
  {"front" => "具", "back" => "tool", "chapter" => "5", "new" => "no"},
  {"front" => "真", "back" => "true", "chapter" => "5", "new" => "no"},
  {"front" => "工", "back" => "work [n]", "chapter" => "5", "new" => "no"},
  {"front" => "左", "back" => "left [n/adj]", "chapter" => "5", "new" => "no"},
  {"front" => "右", "back" => "right [n/adj]", "chapter" => "5", "new" => "no"},
  {"front" => "有", "back" => "possess", "chapter" => "5", "new" => "no"},
  {"front" => "贿", "back" => "bribe [n]", "chapter" => "5", "new" => "no"},
  {"front" => "贡", "back" => "tribute", "chapter" => "5", "new" => "no"},
  {"front" => "项", "back" => "item", "chapter" => "5", "new" => "no"},
  {"front" => "刀", "back" => "sword (dagger / saber)", "chapter" => "5", "new" => "no"},
  {"front" => "仞", "back" => "blade", "chapter" => "5", "new" => "no"},
  {"front" => "切", "back" => "cut [v]", "chapter" => "5", "new" => "no"},
  {"front" => "召", "back" => "summon", "chapter" => "5", "new" => "no"},
  {"front" => "昭", "back" => "evident", "chapter" => "5", "new" => "no"},
  {"front" => "则", "back" => "rule [n]", "chapter" => "5", "new" => "no"},
  {"front" => "副", "back" => "vice-", "chapter" => "5", "new" => "no"},
  {"front" => "丁", "back" => "fourth (nail / spike)", "chapter" => "5", "new" => "no"},
  {"front" => "叮", "back" => "sting [v]", "chapter" => "5", "new" => "no"},
  {"front" => "可", "back" => "can [ad.v]", "chapter" => "5", "new" => "no"},
  {"front" => "哥", "back" => "older brother", "chapter" => "5", "new" => "no"},
  {"front" => "顶", "back" => "crest", "chapter" => "5", "new" => "no"}

  #Lesson 6
#  {"back" => "second", "front" => "乙", "chapter" => "6", "new" => "new"},
#  {"back" => "fly", "front" => "飞", "chapter" => "6", "new" => "new"},
#  {"back" => "child", "front" => "子", "chapter" => "6", "new" => "new"},
#  {"back" => "cavity", "front" => "孔", "chapter" => "6", "new" => "new"},
#  {"back" => "roar", "front" => "吼", "chapter" => "6", "new" => "new"},
#  {"back" => "chaos", "front" => "乱", "chapter" => "6", "new" => "new"},
#  {"back" => "(-ed)", "front" => "了", "chapter" => "6", "new" => "new"},
#  {"back" => "female", "front" => "女", "chapter" => "6", "new" => "new"},
#  {"back" => "good", "front" => "好", "chapter" => "6", "new" => "new"},
#  {"back" => "be like", "front" => "如", "chapter" => "6", "new" => "new"},
#  {"back" => "mother", "front" => "母", "chapter" => "6", "new" => "new"},
#  {"back" => "pierce", "front" => "贯", "chapter" => "6", "new" => "new"},
#  {"back" => "elder brother", "front" => "兄", "chapter" => "6", "new" => "new"},
#  {"back" => "overcome", "front" => "克", "chapter" => "6", "new" => "new"},
  #Lesson 7
#  {"back" => "small", "front" => "小", "chapter" => "7", "new" => "new"},
#  {"back" => "few", "front" => "少", "chapter" => "7", "new" => "new"},
#  {"back" => "noisy", "front" => "吵", "chapter" => "7", "new" => "new"},
#  {"back" => "grandchild", "front" => "孙", "chapter" => "7", "new" => "new"},
#  {"back" => "large", "front" => "大", "chapter" => "7", "new" => "new"},
#  {"back" => "tip", "front" => "尖", "chapter" => "7", "new" => "new"},
#  {"back" => "evening", "front" => "夕", "chapter" => "7", "new" => "new"},
#  {"back" => "many", "front" => "多", "chapter" => "7", "new" => "new"},
#  {"back" => "enough", "front" => "够", "chapter" => "7", "new" => "new"},
#  {"back" => "outside", "front" => "外", "chapter" => "7", "new" => "new"},
#  {"back" => "name", "front" => "名", "chapter" => "7", "new" => "new"},
#  {"back" => "silk gauze", "front" => "罗", "chapter" => "7", "new" => "new"},
#  {"back" => "factory", "front" => "厂", "chapter" => "7", "new" => "new"},
#  {"back" => "hall", "front" => "厅", "chapter" => "7", "new" => "new"},
#  {"back" => "stern", "front" => "历", "chapter" => "7", "new" => "new"},
#  {"back" => "thick", "front" => "厚", "chapter" => "7", "new" => "new"},
#  {"back" => "stone", "front" => "石", "chapter" => "7", "new" => "new"},
#  {"back" => "gravel", "front" => "砂", "chapter" => "7", "new" => "new"},
#  {"back" => "wonderful", "front" => "秒", "chapter" => "7", "new" => "new"},
#  {"back" => "resemble", "front" => "肖", "chapter" => "7", "new" => "new"},
#  {"back" => "peel", "front" => "削", "chapter" => "7", "new" => "new"},
#  {"back" => "ray", "front" => "光", "chapter" => "7", "new" => "new"},
#  {"back" => "overly", "front" => "太", "chapter" => "7", "new" => "new"},
#  {"back" => "economise", "front" => "省", "chapter" => "7", "new" => "new"},
#  {"back" => "strange", "front" => "奇", "chapter" => "7", "new" => "new"},
  #Lesson 8
#  {"back" => "stream", "front" => "川", "chapter" => "8", "new" => "new"},
#  {"back" => "state", "front" => "州", "chapter" => "8", "new" => "new"},
#  {"back" => "obey", "front" => "顺", "chapter" => "8", "new" => "new"},
#  {"back" => "water", "front" => "水", "chapter" => "8", "new" => "new"},
#  {"back" => "eternity", "front" => "永", "chapter" => "8", "new" => "new"},
#  {"back" => "blood vessels", "front" => "脉", "chapter" => "8", "new" => "new"},
#  {"back" => "request", "front" => "求", "chapter" => "8", "new" => "new"},
#  {"back" => "spring", "front" => "泉", "chapter" => "8", "new" => "new"},
#  {"back" => "flatlands", "front" => "原", "chapter" => "8", "new" => "new"},
#  {"back" => "swim", "front" => "泳", "chapter" => "8", "new" => "new"},
#  {"back" => "continent", "front" => "洲", "chapter" => "8", "new" => "new"},
#  {"back" => "marsh", "front" => "沼", "chapter" => "8", "new" => "new"},
#  {"back" => "sand", "front" => "沙", "chapter" => "8", "new" => "new"},
#  {"back" => "Yangtze", "front" => "江", "chapter" => "8", "new" => "new"},
#  {"back" => "juice", "front" => "汁", "chapter" => "8", "new" => "new"},
#  {"back" => "tide", "front" => "潮", "chapter" => "8", "new" => "new"},
#  {"back" => "source", "front" => "源", "chapter" => "8", "new" => "new"},
#  {"back" => "extinguish", "front" => "消", "chapter" => "8", "new" => "new"},
#  {"back" => "river", "front" => "河", "chapter" => "8", "new" => "new"},
#  {"back" => "fish", "front" => "鱼", "chapter" => "8", "new" => "new"},
#  {"back" => "fishing", "front" => "渔", "chapter" => "8", "new" => "new"},
#  {"back" => "lake", "front" => "湖", "chapter" => "8", "new" => "new"},
#  {"back" => "fathom", "front" => "测", "chapter" => "8", "new" => "new"},
#  {"back" => "soil", "front" => "土", "chapter" => "8", "new" => "new"},
#  {"back" => "equal", "front" => "均", "chapter" => "8", "new" => "new"},
#  {"back" => "belly", "front" => "肚", "chapter" => "8", "new" => "new"},
#  {"back" => "dust", "front" => "尘", "chapter" => "8", "new" => "new"},
#  {"back" => "fill in", "front" => "填", "chapter" => "8", "new" => "new"},
#  {"back" => "spit", "front" => "吐", "chapter" => "8", "new" => "new"},
#  {"back" => "pressure", "front" => "压", "chapter" => "8", "new" => "new"},
#  {"back" => "waaah!", "front" => "哇", "chapter" => "8", "new" => "new"},
#  {"back" => "Chinese inch", "front" => "寸", "chapter" => "8", "new" => "new"},
#  {"back" => "seal", "front" => "封", "chapter" => "8", "new" => "new"},
#  {"back" => "time", "front" => "时", "chapter" => "8", "new" => "new"},
#  {"back" => "Buddhist temple", "front" => "寺", "chapter" => "8", "new" => "new"},
#  {"back" => "fire", "front" => "火", "chapter" => "8", "new" => "new"},
#  {"back" => "destroy", "front" => "灭", "chapter" => "8", "new" => "new"},
#  {"back" => "ashes", "front" => "灰", "chapter" => "8", "new" => "new"},
#  {"back" => "vexed", "front" => "烦", "chapter" => "8", "new" => "new"},
#  {"back" => "inflammation", "front" => "炎", "chapter" => "8", "new" => "new"},
#  {"back" => "thin", "front" => "淡", "chapter" => "8", "new" => "new"},
#  {"back" => "lamp", "front" => "灯", "chapter" => "8", "new" => "new"},
#  {"back" => "spot", "front" => "点", "chapter" => "8", "new" => "new"},
#  {"back" => "illuminate", "front" => "照", "chapter" => "8", "new" => "new"},
  #Lesson 9
#  {"back" => "li (about 500m)", "front" => "里", "chapter" => "9", "new" => "new"},
#  {"back" => "quantity", "front" => "量", "chapter" => "9", "new" => "new"},
#  {"back" => "bury", "front" => "埋", "chapter" => "9", "new" => "new"},
#  {"back" => "black", "front" => "黑", "chapter" => "9", "new" => "new"},
#  {"back" => "black ink", "front" => "墨", "chapter" => "9", "new" => "new"},
#  {"back" => "risk", "front" => "冒", "chapter" => "9", "new" => "new"},
#  {"back" => "same", "front" => "同", "chapter" => "9", "new" => "new"},
#  {"back" => "cave", "front" => "洞", "chapter" => "9", "new" => "new"},
#  {"back" => "lovely", "front" => "丽", "chapter" => "9", "new" => "new"},
#  {"back" => "orientation", "front" => "向", "chapter" => "9", "new" => "new"},
#  {"back" => "echo", "front" => "响", "chapter" => "9", "new" => "new"},
#  {"back" => "esteem", "front" => "尚", "chapter" => "9", "new" => "new"},
#  {"back" => "character", "front" => "字", "chapter" => "9", "new" => "new"},
#  {"back" => "guard", "front" => "守", "chapter" => "9", "new" => "new"},
#  {"back" => "finish", "front" => "完", "chapter" => "9", "new" => "new"},
#  {"back" => "disaster", "front" => "灾", "chapter" => "9", "new" => "new"},
#  {"back" => "proclaim", "front" => "宣", "chapter" => "9", "new" => "new"},
#  {"back" => "nighttime", "front" => "宵", "chapter" => "9", "new" => "new"},
#  {"back" => "peaceful", "front" => "安", "chapter" => "9", "new" => "new"},
#  {"back" => "banquet", "front" => "宴", "chapter" => "9", "new" => "new"},
#  {"back" => "mail", "front" => "寄", "chapter" => "9", "new" => "new"},
#  {"back" => "wealthy", "front" => "富", "chapter" => "9", "new" => "new"},
#  {"back" => "store up", "front" => "贮", "chapter" => "9", "new" => "new"},
  #Lesson 10
#  {"back" => "tree", "front" => "木", "chapter" => "10", "new" => "new"},
#  {"back" => "woods", "front" => "林", "chapter" => "10", "new" => "new"},
#  {"back" => "forest", "front" => "森", "chapter" => "10", "new" => "new"},
#  {"back" => "dreams", "front" => "梦", "chapter" => "10", "new" => "new"},
#  {"back" => "machine", "front" => "机", "chapter" => "10", "new" => "new"},
#  {"back" => "plant", "front" => "值", "chapter" => "10", "new" => "new"},
#  {"back" => "apricot", "front" => "杏", "chapter" => "10", "new" => "new"},
#  {"back" => "dim-witted", "front" => "呆", "chapter" => "10", "new" => "new"},
#  {"back" => "withered", "front" => "枯", "chapter" => "10", "new" => "new"},
#  {"back" => "village", "front" => "忖", "chapter" => "10", "new" => "new"},
#  {"back" => "one another", "front" => "相", "chapter" => "10", "new" => "new"},
#  {"back" => "notebook", "front" => "本", "chapter" => "10", "new" => "new"},
#  {"back" => "case", "front" => "案", "chapter" => "10", "new" => "new"},
#  {"back" => "not yet", "front" => "未", "chapter" => "10", "new" => "new"},
#  {"back" => "last", "front" => "末", "chapter" => "10", "new" => "new"},
#  {"back" => "foam", "front" => "沫", "chapter" => "10", "new" => "new"},
#  {"back" => "flavour", "front" => "味", "chapter" => "10", "new" => "new"},
#  {"back" => "younger sister", "front" => "妹", "chapter" => "10", "new" => "new"},
#  {"back" => "investigate", "front" => "查", "chapter" => "10", "new" => "new"},
#  {"back" => "sediment", "front" => "渣", "chapter" => "10", "new" => "new"},
#  {"back" => "dye", "front" => "染", "chapter" => "10", "new" => "new"},
#  {"back" => "plum", "front" => "李", "chapter" => "10", "new" => "new"},
#  {"back" => "table", "front" => "桌", "chapter" => "10", "new" => "new"},
#  {"back" => "miscellaneous", "front" => "杂", "chapter" => "10", "new" => "new"},
#  {"back" => "as if", "front" => "若", "chapter" => "10", "new" => "new"},
#  {"back" => "grass", "front" => "草", "chapter" => "10", "new" => "new"},
#  {"back" => "technique", "front" => "艺", "chapter" => "10", "new" => "new"},
#  {"back" => "suffering", "front" => "苦", "chapter" => "10", "new" => "new"},
#  {"back" => "wide", "front" => "宽", "chapter" => "10", "new" => "new"},
#  {"back" => "nobody", "front" => "莫", "chapter" => "10", "new" => "new"},
#  {"back" => "imitate", "front" => "摸", "chapter" => "10", "new" => "new"},
#  {"back" => "desert", "front" => "漠", "chapter" => "10", "new" => "new"},
#  {"back" => "grave", "front" => "幕", "chapter" => "10", "new" => "new"},
#  {"back" => "seedling", "front" => "苗", "chapter" => "10", "new" => "new"},
#  {"back" => "aim", "front" => "瞄", "chapter" => "10", "new" => "new"},
  #Lesson 11
#  {"back" => "portent", "front" => "兆", "chapter" => "11", "new" => "new"},
#  {"back" => "peach", "front" => "桃", "chapter" => "11", "new" => "new"},
#  {"back" => "pooch", "front" => "犬", "chapter" => "11", "new" => "new"},
#  {"back" => "remarkable", "front" => "尤", "chapter" => "11", "new" => "new"},
#  {"back" => "detest", "front" => "厌", "chapter" => "11", "new" => "new"},
#  {"back" => "state of affairs", "front" => "状", "chapter" => "11", "new" => "new"},
#  {"back" => "put on makeup", "front" => "妆", "chapter" => "11", "new" => "new"},
#  {"back" => "general (military rank)", "front" => "将", "chapter" => "11", "new" => "new"},
#  {"back" => "seize", "front" => "获", "chapter" => "11", "new" => "new"},
#  {"back" => "silent", "front" => "默", "chapter" => "11", "new" => "new"},
#  {"back" => "sort of thing", "front" => "然", "chapter" => "11", "new" => "new"},
#  {"back" => "cry", "front" => "哭", "chapter" => "11", "new" => "new"},
#  {"back" => "utensil", "front" => "器", "chapter" => "11", "new" => "new"},
#  {"back" => "stinking (with drop）臭", "chapter" => "11", "new" => "new"},
#  {"back" => "dog", "front" => "狗", "chapter" => "11", "new" => "new"},
#  {"back" => "cow", "front" => "牛", "chapter" => "11", "new" => "new"},
#  {"back" => "special", "front" => "特", "chapter" => "11", "new" => "new"},
#  {"back" => "declare", "front" => "告", "chapter" => "11", "new" => "new"},
#  {"back" => "vast", "front" => "浩", "chapter" => "11", "new" => "new"},
#  {"back" => "before", "front" => "先", "chapter" => "11", "new" => "new"},
#  {"back" => "wash", "front" => "洗", "chapter" => "11", "new" => "new"},
  #Lesson 12
#  {"back" => "individual", "front" => "个", "chapter" => "12", "new" => "new"},
#  {"back" => "introduce", "front" => "介", "chapter" => "12", "new" => "new"},
#  {"back" => "world", "front" => "界", "chapter" => "12", "new" => "new"},
#  {"back" => "tea", "front" => "茶", "chapter" => "12", "new" => "new"},
#  {"back" => "fit", "front" => "合", "chapter" => "12", "new" => "new"},
#  {"back" => "ha!", "front" => "哈", "chapter" => "12", "new" => "new"},
#  {"back" => "pagoda", "front" => "塔", "chapter" => "12", "new" => "new"},
#  {"back" => "king", "front" => "王", "chapter" => "12", "new" => "new"},
#  {"back" => "jade", "front" => "玉", "chapter" => "12", "new" => "new"},
#  {"back" => "treasure", "front" => "宝", "chapter" => "12", "new" => "new"},
#  {"back" => "ball", "front" => "球", "chapter" => "12", "new" => "new"},
#  {"back" => "present", "front" => "现", "chapter" => "12", "new" => "new"},
#  {"back" => "play", "front" => "玩", "chapter" => "12", "new" => "new"},
#  {"back" => "crazy", "front" => "狂", "chapter" => "12", "new" => "new"},
#  {"back" => "emperor", "front" => "皇", "chapter" => "12", "new" => "new"},
#  {"back" => "resplendent", "front" => "煌", "chapter" => "12", "new" => "new"},
#  {"back" => "submit", "front" => "呈", "chapter" => "12", "new" => "new"},
#  {"back" => "whole", "front" => "全", "chapter" => "12", "new" => "new"},
#  {"back" => "logic", "front" => "理", "chapter" => "12", "new" => "new"},
#  {"back" => "lord", "front" => "主", "chapter" => "12", "new" => "new"},
#  {"back" => "pour", "front" => "住", "chapter" => "12", "new" => "new"},
#  {"back" => "gold", "front" => "金", "chapter" => "12", "new" => "new"},
#  {"back" => "bell", "front" => "钟", "chapter" => "12", "new" => "new"},
#  {"back" => "copper", "front" => "铜", "chapter" => "12", "new" => "new"},
#  {"back" => "go fishing", "front" => "钓", "chapter" => "12", "new" => "new"},
#  {"back" => "needle", "front" => "针", "chapter" => "12", "new" => "new"},
#  {"back" => "nail", "front" => "钉", "chapter" => "12", "new" => "new"},
#  {"back" => "inscription", "front" => "铭", "chapter" => "12", "new" => "new"},
#  {"back" => "at ease", "front" => "镇", "chapter" => "12", "new" => "new"},
  #Lesson 13
#  {"back" => "way", "front" => "道", "chapter" => "13", "new" => "new"},
#  {"back" => "reach", "front" => "达", "chapter" => "13", "new" => "new"},
#  {"back" => "distant", "front" => "远", "chapter" => "13", "new" => "new"},
#  {"back" => "suitable (less one drop) 适", "chapter" => "13", "new" => "new"},
#  {"back" => "cross", "front" => "过", "chapter" => "13", "new" => "new"},
#  {"back" => "stride", "front" => "迈", "chapter" => "13", "new" => "new"},
#  {"back" => "speedy", "front" => "讯", "chapter" => "13", "new" => "new"},
#  {"back" => "create", "front" => "造", "chapter" => "13", "new" => "new"},
#  {"back" => "escape", "front" => "逃", "chapter" => "13", "new" => "new"},
#  {"back" => "patrol", "front" => "巡", "chapter" => "13", "new" => "new"},
#  {"back" => "choose", "front" => "选", "chapter" => "13", "new" => "new"},
#  {"back" => "modest", "front" => "逊", "chapter" => "13", "new" => "new"},
#  {"back" => "stroll", "front" => "逛", "chapter" => "13", "new" => "new"},
#  {"back" => "car", "front" => "车", "chapter" => "13", "new" => "new"},
#  {"back" => "one after another", "front" => "连", "chapter" => "13", "new" => "new"},
#  {"back" => "lotus", "front" => "莲", "chapter" => "13", "new" => "new"},
#  {"back" => "in front", "front" => "前", "chapter" => "13", "new" => "new"},
#  {"back" => "shears", "front" => "剪", "chapter" => "13", "new" => "new"},
#  {"back" => "transport", "front" => "输", "chapter" => "13", "new" => "new"},
#  {"back" => "exceed", "front" => "谕", "chapter" => "13", "new" => "new"},
#  {"back" => "strip", "front" => "条", "chapter" => "13", "new" => "new"},
#  {"back" => "location", "front" => "处", "chapter" => "13", "new" => "new"},
#  {"back" => "each", "front" => "各", "chapter" => "13", "new" => "new"},
#  {"back" => "pattern", "front" => "格", "chapter" => "13", "new" => "new"},
#  {"back" => "abbreviation", "front" => "略", "chapter" => "13", "new" => "new"},
#  {"back" => "guest", "front" => "客", "chapter" => "13", "new" => "new"},
#  {"back" => "forehead", "front" => "额", "chapter" => "13", "new" => "new"},
#  {"back" => "summer", "front" => "夏", "chapter" => "13", "new" => "new"},
#  {"back" => "L.A.", "front" => "洛", "chapter" => "13", "new" => "new"},
#  {"back" => "fall", "front" => "落", "chapter" => "13", "new" => "new"},
#  {"back" => "prepare", "front" => "备", "chapter" => "13", "new" => "new"}
  ]
  
add_cards_to_forward_deck forward_deck, cards
add_cards_to_reverse_deck reverse_deck, cards


forward_deck = get_or_create_deck 'ACCS - Twers (reading practice)', user.id, true, false, 'front'
reverse_deck = get_or_create_deck 'ACCS - Twers (writing practice)', user.id, true, false, 'front'
typing_deck = get_or_create_deck 'ACCS - Twers (typing practice)', user.id, true, true, 'back'


cards = []
cards = [
  #Lesson 1
  {"front" => "一", "back" => "1", "pronunciation" => "yī", "chapter" => "1", "new" => "no"},
  {"front" => "二", "back" => "2", "pronunciation" => "èr", "chapter" => "1", "new" => "no"},
  {"front" => "三", "back" => "3", "pronunciation" => "sān", "chapter" => "1", "new" => "no"},
  {"front" => "四", "back" => "4", "pronunciation" => "sì", "chapter" => "1", "new" => "no"},
  {"front" => "五", "back" => "5", "pronunciation" => "wŭ", "chapter" => "1", "new" => "no"},
  {"front" => "六", "back" => "6", "pronunciation" => "liù", "chapter" => "1", "new" => "no"},
  {"front" => "七", "back" => "7", "pronunciation" => "qī", "chapter" => "1", "new" => "no"},
  {"front" => "八", "back" => "8", "pronunciation" => "bā", "chapter" => "1", "new" => "no"},
  {"front" => "九", "back" => "9", "pronunciation" => "jiŭ", "chapter" => "1", "new" => "no"},
  {"front" => "十", "back" => "10", "pronunciation" => "shí", "chapter" => "1", "new" => "no"},
  {"front" => "女", "back" => "female", "pronunciation" => "nǚ", "chapter" => "1", "new" => "no"},
  {"front" => "安", "back" => "peace", "pronunciation" => "ān", "chapter" => "1", "new" => "no"},
  {"front" => "子", "back" => "child", "pronunciation" => "zǐ", "chapter" => "1", "new" => "no"},
  {"front" => "好", "back" => "good", "pronunciation" => "hăo", "chapter" => "1", "new" => "no"},
  {"front" => "人", "back" => "Man / mankind", "pronunciation" => "rén", "chapter" => "1", "new" => "no"},
  {"front" => "大", "back" => "big", "pronunciation" => "dà", "chapter" => "1", "new" => "no"},
  {"front" => "太", "back" => "excessive", "pronunciation" => "tài", "chapter" => "1", "new" => "no"},
  {"front" => "天", "back" => "sky", "pronunciation" => "tiān", "chapter" => "1", "new" => "no"},
  {"front" => "日", "back" => "sun", "pronunciation" => "rì", "chapter" => "1", "new" => "no"},
  {"front" => "月", "back" => "moon", "pronunciation" => "yuè", "chapter" => "1", "new" => "no"},
  {"front" => "明", "back" => "bright", "pronunciation" => "míng", "chapter" => "1", "new" => "no"},
  {"front" => "白", "back" => "clear", "pronunciation" => "bái", "chapter" => "1", "new" => "no"},
  {"front" => "明白", "back" => "understand", "pronunciation" => "míng bái", "chapter" => "1", "new" => "no"},
  {"front" => "晶", "back" => "crystal", "pronunciation" => "jīng", "chapter" => "1", "new" => "no"},
  {"front" => "旦", "back" => "dawn", "pronunciation" => "dàn", "chapter" => "1", "new" => "no"},
  {"front" => "字", "back" => "word", "pronunciation" => "zì", "chapter" => "1", "new" => "no"},
  {"front" => "早", "back" => "early", "pronunciation" => "zăo", "chapter" => "1", "new" => "no"},
  {"front" => "百", "back" => "hundred", "pronunciation" => "băi", "chapter" => "1", "new" => "no"},
  {"front" => "千", "back" => "thousand", "pronunciation" => "qiān", "chapter" => "1", "new" => "no"},
  {"front" => "万", "back" => "ten thousand", "pronunciation" => "wàn", "chapter" => "1", "new" => "no"},
  {"front" => "亿", "back" => "hundred million", "pronunciation" => "yì", "chapter" => "1", "new" => "no"},
  {"front" => "女人", "back" => "woman", "pronunciation" => "nǚ rén", "chapter" => "1", "new" => "no"},
  {"front" => "早安", "back" => "good morning", "pronunciation" => "zăo ān", "chapter" => "1", "new" => "no"},
  {"front" => "大人", "back" => "adult / big man", "pronunciation" => "dà rén", "chapter" => "1", "new" => "no"},
  {"front" => "太太", "back" => "Mrs", "pronunciation" => "tài tài", "chapter" => "1", "new" => "no"},
  {"front" => "白天", "back" => "daytime", "pronunciation" => "bái tiān", "chapter" => "1", "new" => "no"},
  {"front" => "明天", "back" => "tomorrow", "pronunciation" => "míng tiān", "chapter" => "1", "new" => "no"},
  {"front" => "天天", "back" => "everyday", "pronunciation" => "tiān tiān", "chapter" => "1", "new" => "no"},
  {"front" => "太大", "back" => "too big", "pronunciation" => "tài dà", "chapter" => "1", "new" => "no"},
  {"front" => "好人", "back" => "good person", "pronunciation" => "hăo rén", "chapter" => "1", "new" => "no"},
  {"front" => "零", "back" => "zero", "pronunciation" => "lìng", "chapter" => "1", "new" => "no"},
  #Lesson 2
  {"front" => "小", "back" => "small", "pronunciation" => "xiăo", "chapter" => "2", "new" => "no"},
  {"front" => "也", "back" => "also[adv]", "pronunciation" => "yĕ", "chapter" => "2", "new" => "no"},
  {"front" => "他", "back" => "he/him", "pronunciation" => "tā", "chapter" => "2", "new" => "no"},
  {"front" => "她", "back" => "she/her", "pronunciation" => "tā", "chapter" => "2", "new" => "no"},
  {"front" => "心", "back" => "heart", "pronunciation" => "xīn", "chapter" => "2", "new" => "no"},
  {"front" => "目", "back" => "eyes", "pronunciation" => "mù", "chapter" => "2", "new" => "no"},
  {"front" => "见", "back" => "see[v]", "pronunciation" => "jiàn", "chapter" => "2", "new" => "no"},
  {"front" => "门", "back" => "door", "pronunciation" => "mén", "chapter" => "2", "new" => "no"},
  {"front" => "们", "back" => "plural", "pronunciation" => "men", "chapter" => "2", "new" => "no"},
  {"front" => "人们", "back" => "people", "pronunciation" => "rén men", "chapter" => "2", "new" => "no"},
  {"front" => "手", "back" => "hand", "pronunciation" => "shǒu", "chapter" => "2", "new" => "no"},
  {"front" => "戈", "back" => "spear", "pronunciation" => "gē", "chapter" => "2", "new" => "no"},
  {"front" => "我", "back" => "I/me[pron]", "pronunciation" => "wǒ", "chapter" => "2", "new" => "no"},
  {"front" => "看", "back" => "look", "pronunciation" => "kàn", "chapter" => "2", "new" => "no"},
  {"front" => "你", "back" => "you", "pronunciation" => "nǐ", "chapter" => "2", "new" => "no"},
  {"front" => "不", "back" => "not[adj]", "pronunciation" => "bù", "chapter" => "2", "new" => "no"},
  {"front" => "了", "back" => "[a modal participle]", "pronunciation" => "le", "chapter" => "2", "new" => "no"},
  {"front" => "吗", "back" => "[an interrogative participle]", "pronunciation" => "ma", "chapter" => "2", "new" => "no"},
  {"front" => "很", "back" => "very[adv]", "pronunciation" => "hěn", "chapter" => "2", "new" => "no"},
  {"front" => "小心", "back" => "be careful", "pronunciation" => "xiăo xīn", "chapter" => "2", "new" => "no"},
  {"front" => "谢谢", "back" => "thank you[v]", "pronunciation" => "xiè xie", "chapter" => "2", "new" => "no"},
  {"front" => "问好", "back" => "to greet[v]; greeting[n]", "pronunciation" => "wèn hòu", "chapter" => "2", "new" => "no"},
  {"front" => "你好", "back" => "hello", "pronunciation" => "nǐ hǎo", "chapter" => "2", "new" => "no"},
  {"front" => "好久", "back" => "long time[adj]", "pronunciation" => "hǎo jiŭ", "chapter" => "2", "new" => "no"},
  {"front" => "心目", "back" => "mood, memory", "pronunciation" => "xīn mù", "chapter" => "2", "new" => "no"},
  {"front" => "安心", "back" => "feel at ease / not worried", "pronunciation" => "ān xīn", "chapter" => "2", "new" => "no"},
  {"front" => "好心人", "back" => "kind-hearted person", "pronunciation" => "hǎo xīn rén", "chapter" => "2", "new" => "no"},
  {"front" => "看见", "back" => "see", "pronunciation" => "kàn jiàn", "chapter" => "2", "new" => "no"},
  {"front" => "明天见", "back" => "see you tomorrow", "pronunciation" => "míng tiān jiàn", "chapter" => "2", "new" => "no"},
  {"front" => "太小", "back" => "too small", "pronunciation" => "tāi xiăo", "chapter" => "2", "new" => "no"},
  {"front" => "你们", "back" => "all of you", "pronunciation" => "nǐ men", "chapter" => "2", "new" => "no"},
  {"front" => "他们", "back" => "they / them", "pronunciation" => "tā men", "chapter" => "2", "new" => "no"},
  {"front" => "她们", "back" => "(female) they", "pronunciation" => "tā men", "chapter" => "2", "new" => "no"},
  {"front" => "我们", "back" => "we / us", "pronunciation" => "wǒ men", "chapter" => "2", "new" => "no"},
  {"front" => "你早", "back" => "good mornǐng", "pronunciation" => "nǐ zǎo", "chapter" => "2", "new" => "no"},
  {"front" => "你们好", "back" => "how do you do, hello", "pronunciation" => "nǐ men hǎo", "chapter" => "2", "new" => "no"},
  {"front" => "您好", "back" => "how do you do, hello (polite)", "pronunciation" => "nǐn hǎo", "chapter" => "2", "new" => "no"},
  {"front" => "好久不见了", "back" => "Long time no see", "pronunciation" => "hǎo jiǔ bú jiàn le", "chapter" => "2", "new" => "no"},
  {"front" => "你好吗？", "back" => "How are you?", "pronunciation" => "nǐ hǎo ma?", "chapter" => "2", "new" => "no"},
  {"front" => "我很好", "back" => "I am fine", "pronunciation" => "Wǒ hěn hǎo", "chapter" => "2", "new" => "no"},
  {"front" => "我也很好", "back" => "I'm also fine", "pronunciation" => "Wǒ yě hěn hǎo", "chapter" => "2", "new" => "no"},
  {"front" => "你太太好吗", "back" => "How is your wife?", "pronunciation" => "nǐ tāi tāi hǎo ma?", "chapter" => "2", "new" => "no"},
  {"front" => "她也很好", "back" => "She is also fine", "pronunciation" => "tā yě hěn hǎo", "chapter" => "2", "new" => "no"},

  #Lesson 3
  {"front" => "开", "back" => "opens", "pronunciation" => "kāi", "chapter" => "3", "new" => "no"},
  {"front" => "口", "back" => "mouth", "pronunciation" => "kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "叫", "back" => "to call", "pronunciation" => "jiào [v]", "chapter" => "3", "new" => "no"},
  {"front" => "马", "back" => "horse", "pronunciation" => "mǎ", "chapter" => "3", "new" => "no"},
  {"front" => "闯", "back" => "rush", "pronunciation" => "chuǎng", "chapter" => "3", "new" => "no"},
  {"front" => "问", "back" => "to ask[v]", "pronunciation" => "wèn", "chapter" => "3", "new" => "no"},
  {"front" => "妈", "back" => "mother", "pronunciation" => "mā", "chapter" => "3", "new" => "no"},
  {"front" => "唱", "back" => "sings", "pronunciation" => "chàng", "chapter" => "3", "new" => "no"},
  {"front" => "门口", "back" => "passage way", "pronunciation" => "mén kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "大门", "back" => "front door", "pronunciation" => "dà mén", "chapter" => "3", "new" => "no"},
  {"front" => "开门", "back" => "open the door", "pronunciation" => "kāi mén", "chapter" => "3", "new" => "no"},
  {"front" => "开口", "back" => "open one's mouth to speak", "pronunciation" => "kāi kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "开心", "back" => "feel happy", "pronunciation" => "kāi xīn", "chapter" => "3", "new" => "no"},
  {"front" => "请问", "back" => "excuse me， may I ask", "pronunciation" => "qǐng wèn", "chapter" => "3", "new" => "no"},
  {"front" => "问题", "back" => "question  / problem", "pronunciation" => "wèn tí", "chapter" => "3", "new" => "no"},
  {"front" => "吗上", "back" => "at once", "pronunciation" => "mǎ shàng", "chapter" => "3", "new" => "no"},
  {"front" => "妈妈", "back" => "mother", "pronunciation" => "māma", "chapter" => "3", "new" => "no"},
  {"front" => "大妈", "back" => "aunty", "pronunciation" => "dà mā", "chapter" => "3", "new" => "no"},
  {"front" => "人口", "back" => "population", "pronunciation" => "rén kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "入口", "back" => "entrance", "pronunciation" => "rù kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "出口", "back" => "exit;export", "pronunciation" => "chū kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "进口", "back" => "entrance;import", "pronunciation" => "jìn kǒu", "chapter" => "3", "new" => "no"},
  {"front" => "姓名", "back" => "fullname [n.]", "pronunciation" => "xìng míng", "chapter" => "3", "new" => "no"},
  {"front" => "贵姓", "back" => "Your honourable surname", "pronunciation" => "guì xìng", "chapter" => "3", "new" => "no"},
  {"front" => "姓", "back" => "surname[v;n]", "pronunciation" => "xìng", "chapter" => "3", "new" => "no"},
  {"front" => "什么", "back" => "what[pron]", "pronunciation" => "shén me", "chapter" => "3", "new" => "no"},
  {"front" => "名字", "back" => "name[n]", "pronunciation" => "míng zi", "chapter" => "3", "new" => "no"},
  {"front" => "见到", "back" => "to see; to have seen", "pronunciation" => "jiàn dào", "chapter" => "3", "new" => "no"},
  {"front" => "您", "back" => "you(polite)", "pronunciation" => "nín", "chapter" => "3", "new" => "no"},
  {"front" => "高兴", "back" => "happy glad[adj]", "pronunciation" => "gāo xìng", "chapter" => "3", "new" => "no"},
  {"front" => "请问， 您贵姓", "back" => "Excuse me, may I know your surname?", "pronunciation" => "qǐng wèn, nín guì xìng", "chapter" => "3", "new" => "no"},
  {"front" => "我姓...， 叫...", "back" => "My surname is ..., my given name is ...", "pronunciation" => "wǒ xìng ?, jiào ?", "chapter" => "3", "new" => "no"},
  {"front" => "您叫什么名字", "back" => "What is your name?", "pronunciation" => "nín jiào shén me míng zi", "chapter" => "3", "new" => "no"},
  {"front" => "我叫。。。", "back" => "My name is...", "pronunciation" => "wǒ jiào...", "chapter" => "3", "new" => "no"},
  {"front" => "见到您， 我很高兴。", "back" => "I am pleased to meet you.", "pronunciation" => "jiàn dào nín, wǒ hěn gāo xìng", "chapter" => "3", "new" => "no"},
  {"front" => "见到您， 我也很高兴。", "back" => "I am also please to meet you.", "pronunciation" => "jiàn dào nín, wǒ yě hěn gāo xìng", "chapter" => "3", "new" => "no"},


  #lesson 4
  {"front" => "下", "back" => "down, below", "pronunciation" => "xià", "chapter" => "4", "new" => "no"},
  {"front" => "上", "back" => "up, above", "pronunciation" => "shàng", "chapter" => "4", "new" => "no"},
  {"front" => "是", "back" => "to be, yes, is", "pronunciation" => "shì", "chapter" => "4", "new" => "no"},
  {"front" => "土", "back" => "earth", "pronunciation" => "tŭ", "chapter" => "4", "new" => "no"},
  {"front" => "走", "back" => "walk", "pronunciation" => "zǒu", "chapter" => "4", "new" => "no"},
  {"front" => "尘", "back" => "dust", "pronunciation" => "chén", "chapter" => "4", "new" => "no"},
  {"front" => "坐", "back" => "sit", "pronunciation" => "zuò", "chapter" => "4", "new" => "no"},
  {"front" => "去", "back" => "go", "pronunciation" => "qù", "chapter" => "4", "new" => "no"},
  {"front" => "先", "back" => "first", "pronunciation" => "xiān", "chapter" => "4", "new" => "no"},
  {"front" => "生", "back" => "grow", "pronunciation" => "shēng", "chapter" => "4", "new" => "no"},
  {"front" => "夕", "back" => "evening", "pronunciation" => "xī", "chapter" => "4", "new" => "no"},
  {"front" => "多", "back" => "many", "pronunciation" => "duō", "chapter" => "4", "new" => "no"},
  {"front" => "名", "back" => "given name", "pronunciation" => "míng", "chapter" => "4", "new" => "no"},
  {"front" => "朋", "back" => "friend, companion", "pronunciation" => "péng", "chapter" => "4", "new" => "no"},
  {"front" => "友", "back" => "friend", "pronunciation" => "yǒu", "chapter" => "4", "new" => "no"},
  {"front" => "灰", "back" => "grey", "pronunciation" => "huī", "chapter" => "4", "new" => "no"},
  {"front" => "兴", "back" => "glad, pleased", "pronunciation" => "xìng", "chapter" => "4", "new" => "no"},
  {"front" => "请", "back" => "please; to invite", "pronunciation" => "qǐng", "chapter" => "4", "new" => "no"},
  {"front" => "这", "back" => "this", "pronunciation" => "zhè", "chapter" => "4", "new" => "no"},
  {"front" => "来", "back" => "to come", "pronunciation" => "lái", "chapter" => "4", "new" => "no"},
  {"front" => "早上", "back" => "in the morning", "pronunciation" => "zǎo shang", "chapter" => "4", "new" => "no"},
  {"front" => "早上好", "back" => "good morning (variation)", "pronunciation" => "zǎo shang hǎo", "chapter" => "4", "new" => "no"},
  {"front" => "坐下", "back" => "sit down", "pronunciation" => "zuò xià", "chapter" => "4", "new" => "no"},
  {"front" => "先生", "back" => "Mr", "pronunciation" => "xiān sheng", "chapter" => "4", "new" => "no"},
  {"front" => "生日", "back" => "birthday", "pronunciation" => "shēng rì", "chapter" => "4", "new" => "no"},
  {"front" => "名人", "back" => "celebrity", "pronunciation" => "míng rén", "chapter" => "4", "new" => "no"},
  {"front" => "这是", "back" => "this is", "pronunciation" => "zhè shì", "chapter" => "4", "new" => "no"},
  {"front" => "这不是", "back" => "this is not", "pronunciation" => "zhè bù shì", "chapter" => "4", "new" => "no"},
  {"front" => "那是", "back" => "that is", "pronunciation" => "nà shì", "chapter" => "4", "new" => "no"},
  {"front" => "那不是", "back" => "that is not", "pronunciation" => "nà bù shì", "chapter" => "4", "new" => "no"},
  {"front" => "我是", "back" => "I am", "pronunciation" => "wǒ shì", "chapter" => "4", "new" => "no"},
  {"front" => "我不是", "back" => "I am not", "pronunciation" => "wǒ bù shì", "chapter" => "4", "new" => "no"},
  {"front" => "灰尘", "back" => "dust (usage)", "pronunciation" => "huī chén", "chapter" => "4", "new" => "no"},
  {"front" => "朋友", "back" => "friend (usage)", "pronunciation" => "péng you", "chapter" => "4", "new" => "no"},
  {"front" => "友好", "back" => "friendly", "pronunciation" => "yǒu hǎo", "chapter" => "4", "new" => "no"},
  {"front" => "请坐", "back" => "Please be seated", "pronunciation" => "qǐng zuò", "chapter" => "4", "new" => "no"},
  {"front" => "介绍", "back" => "to introduce, introduction", "pronunciation" => "jiè shào", "chapter" => "4", "new" => "no"},
  {"front" => "小姐", "back" => "miss", "pronunciation" => "xiǎo jiě", "chapter" => "4", "new" => "no"},
  {"front" => "一下", "back" => "one time, once", "pronunciation" => "yí xià", "chapter" => "4", "new" => "no"},
  {"front" => "夫人", "back" => "wife", "pronunciation" => "fū ren", "chapter" => "4", "new" => "no"},
  {"front" => "我来介绍一下", "back" => "let me introduce you", "pronunciation" => "wǒ lái jiè shào yí xià", "chapter" => "4", "new" => "no"},
  {"front" => "这是我夫人,...", "back" => "this is my wife, ...", "pronunciation" => "zhè shì wǒ fū ren, ...", "chapter" => "4", "new" => "no"},
  {"front" => "他是我朋友", "back" => "He is my friend", "pronunciation" => "ta1 shì wǒ péng you", "chapter" => "4", "new" => "no"},
  {"front" => "她是我朋友", "back" => "She is my friend", "pronunciation" => "ta1 shì wǒ péng you", "chapter" => "4", "new" => "no"},
  {"front" => "见到您， 我很高兴", "back" => "I'm pleased to meet you", "pronunciation" => "jiàn dào nín, wǒ hěn gāo xìng", "chapter" => "4", "new" => "no"},

  #lesson 5
  {"front" => "工", "back" => "work", "pronunciation" => "gōng", "chapter" => "5", "new" => "no"},
  {"front" => "左", "back" => "left", "pronunciation" => "zuǒ", "chapter" => "5", "new" => "no"},
  {"front" => "右", "back" => "right", "pronunciation" => "yòu", "chapter" => "5", "new" => "no"},
  {"front" => "有", "back" => "have", "pronunciation" => "yǒu", "chapter" => "5", "new" => "no"},
  {"front" => "家", "back" => "family", "pronunciation" => "jiā", "chapter" => "5", "new" => "no"},
  {"front" => "嫁", "back" => "marry", "pronunciation" => "jià", "chapter" => "5", "new" => "no"},
  {"front" => "夫", "back" => "husband, distinguished person", "pronunciation" => "fū", "chapter" => "5", "new" => "no"},
  {"front" => "妻", "back" => "wife (variation)", "pronunciation" => "qī", "chapter" => "5", "new" => "no"},
  {"front" => "学", "back" => "study", "pronunciation" => "xué", "chapter" => "5", "new" => "no"},
  {"front" => "吧", "back" => "（a modal particle)", "pronunciation" => "ba", "chapter" => "5", "new" => "no"},
  {"front" => "那", "back" => "which", "pronunciation" => "nǎ", "chapter" => "5", "new" => "no"},
  {"front" => "国", "back" => "nation", "pronunciation" => "guó", "chapter" => "5", "new" => "no"},
  {"front" => "在", "back" => "to be, at", "pronunciation" => "zài", "chapter" => "5", "new" => "no"},
  {"front" => "年", "back" => "year", "pronunciation" => "nián", "chapter" => "5", "new" => "no"},
  {"front" => "的", "back" => "a structural particle", "pronunciation" => "de", "chapter" => "5", "new" => "no"},
  {"front" => "回", "back" => "to return", "pronunciation" => "huí", "chapter" => "5", "new" => "no"},
  {"front" => "工人", "back" => "worker", "pronunciation" => "gōng rén", "chapter" => "5", "new" => "no"},
  {"front" => "手工", "back" => "handiwork", "pronunciation" => "shǒu gōng", "chapter" => "5", "new" => "no"},
  {"front" => "开工", "back" => "go into operation", "pronunciation" => "kāi gōng", "chapter" => "5", "new" => "no"},
  {"front" => "左右", "back" => "about, approximately", "pronunciation" => "zǒu yòu", "chapter" => "5", "new" => "no"},
  {"front" => "有名", "back" => "famous", "pronunciation" => "yǒu míng", "chapter" => "5", "new" => "no"},
  {"front" => "大家", "back" => "all of us", "pronunciation" => "dà jiā", "chapter" => "5", "new" => "no"},
  {"front" => "家人", "back" => "family members", "pronunciation" => "jiā rén", "chapter" => "5", "new" => "no"},
  {"front" => "大夫", "back" => "doctor", "pronunciation" => "dài fu", "chapter" => "5", "new" => "no"},
  {"front" => "丈夫", "back" => "husband", "pronunciation" => "zhàng fu", "chapter" => "5", "new" => "no"},
  {"front" => "夫妻", "back" => "married couple", "pronunciation" => "fū qī", "chapter" => "5", "new" => "no"},
  {"front" => "妻子", "back" => "wife (variation 2)", "pronunciation" => "qī zi", "chapter" => "5", "new" => "no"},
  {"front" => "大学", "back" => "university", "pronunciation" => "dà xué", "chapter" => "5", "new" => "no"},
  {"front" => "中学", "back" => "middle school", "pronunciation" => "zhōng xué", "chapter" => "5", "new" => "no"},
  {"front" => "小学", "back" => "primary school", "pronunciation" => "xiǎo xué", "chapter" => "5", "new" => "no"},
  {"front" => "学生", "back" => "student", "pronunciation" => "xué sheng", "chapter" => "5", "new" => "no"},
  {"front" => "见谈", "back" => "to talk, small talk", "pronunciation" => "jiāo tán", "chapter" => "5", "new" => "no"},
  {"front" => "英文", "back" => "English Language", "pronunciation" => "yīng wén", "chapter" => "5", "new" => "no"},
  {"front" => "哪里", "back" => "where", "pronunciation" => "nǎ lǐ", "chapter" => "5", "new" => "no"},
  {"front" => "我的", "back" => "my", "pronunciation" => "wǒ de", "chapter" => "5", "new" => "no"},
  {"front" => "明年", "back" => "next year", "pronunciation" => "míng nián", "chapter" => "5", "new" => "no"},
  {"front" => "中国人", "back" => "Chinese", "pronunciation" => "zhōng guó rén", "chapter" => "5", "new" => "no"},
  {"front" => "新加坡人", "back" => "Singaporean", "pronunciation" => "xīn jiā pō rén", "chapter" => "5", "new" => "no"},
  {"front" => "澳大利亚", "back" => "Australia", "pronunciation" => "aò dà lì yà", "chapter" => "5", "new" => "no"},
  {"front" => "丁先生你是中国人吧", "back" => "Mr Ding you are from China, aren't you?", "pronunciation" => "dīng xiān sheng, nǐ shì zhōng guó rén ba?", "chapter" => "5", "new" => "no"},
  {"front" => "不实。我是新加坡人", "back" => "No, I'm not. I am Singaporean.", "pronunciation" => "bù shì. wǒ shì xīn jiā pō rén", "chapter" => "5", "new" => "no"},
  {"front" => "吗太太，你是那国人？", "back" => "Mrs Ma, where are you from?", "pronunciation" => "mǎ tài tai, nǐ shì nǎ guó rén", "chapter" => "5", "new" => "no"},
  {"front" => "我是澳大利亚人", "back" => "I am an Australian", "pronunciation" => "wǒ shì aò dà lì yà rén", "chapter" => "5", "new" => "no"},
  {"front" => "丁先生你是学生吗？", "back" => "Are you a student, Mr Ding?", "pronunciation" => "dīng xiān sheng nǐ shì xué sheng ma", "chapter" => "5", "new" => "no"},
  {"front" => "是的。 我在学英文", "back" => "Yes, I am studying English.", "pronunciation" => "shì de. wǒ zài xué yīng wén", "chapter" => "5", "new" => "no"},
  {"front" => "我在澳大利亚一年左右了", "back" => "I've been in Australia for about one year", "pronunciation" => "wǒ zài aò dà lì yà yì nián zuǒ yòu le", "chapter" => "5", "new" => "no"},

  #lesson 6
  {"front" => "田", "back" => "field", "pronunciation" => "tián", "chapter" => "6", "new" => "yes"},
  {"front" => "力", "back" => "strenth", "pronunciation" => "lì", "chapter" => "6", "new" => "yes"},
  {"front" => "男", "back" => "male", "pronunciation" => "nán", "chapter" => "6", "new" => "yes"},
  {"front" => "里", "back" => "mile, village, inside", "pronunciation" => "lǐ", "chapter" => "6", "new" => "yes"},
  {"front" => "胃", "back" => "stomach", "pronunciation" => "wèi", "chapter" => "6", "new" => "yes"},
  {"front" => "王", "back" => "king", "pronunciation" => "wáng", "chapter" => "6", "new" => "yes"},
  {"front" => "玉", "back" => "jade", "pronunciation" => "yù", "chapter" => "6", "new" => "yes"},
  {"front" => "宝", "back" => "precious", "pronunciation" => "bǎo", "chapter" => "6", "new" => "yes"},
  {"front" => "主", "back" => "master", "pronunciation" => "zhǔ", "chapter" => "6", "new" => "yes"},
  {"front" => "住", "back" => "to live, to stay", "pronunciation" => "zhù", "chapter" => "6", "new" => "yes"},
  {"front" => "街", "back" => "street", "pronunciation" => "jiē", "chapter" => "6", "new" => "yes"},
  {"front" => "号", "back" => "number", "pronunciation" => "hào", "chapter" => "6", "new" => "yes"},
  {"front" => "个", "back" => "(measure word)", "pronunciation" => "gé", "chapter" => "6", "new" => "yes"},
  {"front" => "只", "back" => "only", "pronunciation" => "zhǐ", "chapter" => "6", "new" => "yes"},
  {"front" => "两", "back" => "two", "pronunciation" => "liǎng", "chapter" => "6", "new" => "yes"},
  {"front" => "和", "back" => "and", "pronunciation" => "hé", "chapter" => "6", "new" => "yes"},
  {"front" => "玩", "back" => "to play", "pronunciation" => "wán", "chapter" => "6", "new" => "yes"},
  {"front" => "人力", "back" => "man power", "pronunciation" => "rén lì", "chapter" => "6", "new" => "yes"},
  {"front" => "男人", "back" => "man", "pronunciation" => "nán rén", "chapter" => "6", "new" => "yes"},
  {"front" => "女王", "back" => "queen", "pronunciation" => "nǚ wáng", "chapter" => "6", "new" => "yes"},
  {"front" => "国王", "back" => "king (usage)", "pronunciation" => "guó wáng", "chapter" => "6", "new" => "yes"},
  {"front" => "王子", "back" => "prince", "pronunciation" => "wáng zi", "chapter" => "6", "new" => "yes"},
  {"front" => "王国", "back" => "kingdom", "pronunciation" => "wáng guó", "chapter" => "6", "new" => "yes"},
  {"front" => "国家", "back" => "country, state, nation", "pronunciation" => "guó jiā", "chapter" => "6", "new" => "yes"},
  {"front" => "国土", "back" => "territory", "pronunciation" => "guó tǔ", "chapter" => "6", "new" => "yes"},
  {"front" => "主人", "back" => "host", "pronunciation" => "zhǔ rén", "chapter" => "6", "new" => "yes"},
  {"front" => "胃口", "back" => "appetite", "pronunciation" => "wèi kǒu", "chapter" => "6", "new" => "yes"},
  {"front" => "住处", "back" => "living place", "pronunciation" => "zhù chù", "chapter" => "6", "new" => "yes"},
  {"front" => "地址", "back" => "address", "pronunciation" => "dì zhǐ", "chapter" => "6", "new" => "yes"},
  {"front" => "房子", "back" => "house", "pronunciation" => "fáng zi", "chapter" => "6", "new" => "yes"},
  {"front" => "房间", "back" => "room", "pronunciation" => "fáng jiān", "chapter" => "6", "new" => "yes"},
  {"front" => "欢迎", "back" => "to welcome", "pronunciation" => "huān yíng", "chapter" => "6", "new" => "yes"},
  {"front" => "一定", "back" => "certainly", "pronunciation" => "yí dìng", "chapter" => "6", "new" => "yes"},
  {"front" => "吗先生，请来我住处玩", "back" => "Mr Ma, Please come and visit my place", "pronunciation" => "mǎ xiān sheng, qǐng lái wǒ zhù chù wán.", "chapter" => "6", "new" => "yes"},
  {"front" => "好的。你住哪里", "back" => "Alright. Where do you live?", "pronunciation" => "hǎo de. nǐ zhù nǎ lǐ", "chapter" => "6", "new" => "yes"},
  {"front" => "握住在...", "back" => "I live in ...", "pronunciation" => "wǒ zhù zài ...", "chapter" => "6", "new" => "yes"},
  {"front" => "这是我的地址", "back" => "this is my address", "pronunciation" => "zhè shì wǒ de dì zhǐ", "chapter" => "6", "new" => "yes"},
  {"front" => "...街十八号", "back" => "18 ... street", "pronunciation" => "...jiē shí bā hào", "chapter" => "6", "new" => "yes"},
  {"front" => "这房子大不大", "back" => "Is this house big?", "pronunciation" => "zhè fáng zi dà bú dà", "chapter" => "6", "new" => "yes"},
  {"front" => "不大，只有两个房间", "back" => "No, it only has two rooms", "pronunciation" => "bú dà, zhǐ yǒu liǎng gé fáng jiān", "chapter" => "6", "new" => "yes"},
  {"front" => "你一个人住吗？", "back" => "Do you live by yourself?", "pronunciation" => "nǐ yí gé rén zhù ma?", "chapter" => "6", "new" => "yes"},
  {"front" => "不，我和一个奥大剌亚朋友住。欢迎你来玩", "back" => "No, I live with an Australian friend. You are welcome to my place", "pronunciation" => "bù, wǒ hé yí gé ào dà lì ya4 péng you zhù huān yíng nǐ lái wán.", "chapter" => "6", "new" => "yes"},
  {"front" => "谢谢，我一定来", "back" => "Thank you, I will certainly come.", "pronunciation" => "xiè xie, wǒ yí dìng lái", "chapter" => "6", "new" => "yes"},

  #lesson 7
  {"front" => "木", "back" => "tree, wood", "pronunciation" => "mù", "chapter" => "7", "new" => "yes"},
  {"front" => "林", "back" => "forest", "pronunciation" => "lín", "chapter" => "7", "new" => "yes"},
  {"front" => "森", "back" => "dense forest", "pronunciation" => "sēn", "chapter" => "7", "new" => "yes"},
  {"front" => "梦", "back" => "dream", "pronunciation" => "mèng", "chapter" => "7", "new" => "yes"},
  {"front" => "休", "back" => "rest", "pronunciation" => "xiū", "chapter" => "7", "new" => "yes"},
  {"front" => "本", "back" => "root", "pronunciation" => "běn", "chapter" => "7", "new" => "yes"},
  {"front" => "体", "back" => "body", "pronunciation" => "tǐ", "chapter" => "7", "new" => "yes"},
  {"front" => "李", "back" => "plum", "pronunciation" => "lǐ", "chapter" => "7", "new" => "yes"},
  {"front" => "果", "back" => "fruit", "pronunciation" => "guǒ", "chapter" => "7", "new" => "yes"},
  {"front" => "几", "back" => "how many, how much, which, some, a few", "pronunciation" => "jǐ", "chapter" => "7", "new" => "yes"},
  {"front" => "点", "back" => "o'clock", "pronunciation" => "diǎn", "chapter" => "7", "new" => "yes"},
  {"front" => "差", "back" => "less", "pronunciation" => "chà", "chapter" => "7", "new" => "yes"},
  {"front" => "分", "back" => "minute", "pronunciation" => "fēn", "chapter" => "7", "new" => "yes"},
  {"front" => "急", "back" => "urgent", "pronunciation" => "jí", "chapter" => "7", "new" => "yes"},
  {"front" => "事", "back" => "matter, thing", "pronunciation" => "shì", "chapter" => "7", "new" => "yes"},
  {"front" => "要", "back" => "to want", "pronunciation" => "yào", "chapter" => "7", "new" => "yes"},
  {"front" => "会", "back" => "can, be able to, meeting, conference", "pronunciation" => "huì", "chapter" => "7", "new" => "yes"},
  {"front" => "半", "back" => "half", "pronunciation" => "bàn", "chapter" => "7", "new" => "yes"},
  {"front" => "才", "back" => "just", "pronunciation" => "cái", "chapter" => "7", "new" => "yes"},
  {"front" => "还", "back" => "still", "pronunciation" => "hái", "chapter" => "7", "new" => "yes"},
  {"front" => "呢", "back" => "a modal particle", "pronunciation" => "ne", "chapter" => "7", "new" => "yes"},
  {"front" => "想", "back" => "would like to, to think", "pronunciation" => "xiǎng", "chapter" => "7", "new" => "yes"},
  {"front" => "木工", "back" => "woodwork", "pronunciation" => "mù gōng", "chapter" => "7", "new" => "yes"},
  {"front" => "森林", "back" => "forest (usage)", "pronunciation" => "sēn lín", "chapter" => "7", "new" => "yes"},
  {"front" => "做梦", "back" => "to dream", "pronunciation" => "zuò mèng", "chapter" => "7", "new" => "yes"},
  {"front" => "梦见", "back" => "see in a dream", "pronunciation" => "mèng jiàn", "chapter" => "7", "new" => "yes"},
  {"front" => "休息", "back" => "rest (usage)", "pronunciation" => "xiū xi", "chapter" => "7", "new" => "yes"},
  {"front" => "本子", "back" => "notebook", "pronunciation" => "běn zi", "chapter" => "7", "new" => "yes"},
  {"front" => "日本", "back" => "Japan", "pronunciation" => "rì běn", "chapter" => "7", "new" => "yes"},
  {"front" => "身体", "back" => "body, health", "pronunciation" => "shēn tǐ", "chapter" => "7", "new" => "yes"},
  {"front" => "李子", "back" => "plum (usage)", "pronunciation" => "lǐ zi", "chapter" => "7", "new" => "yes"},
  {"front" => "水果", "back" => "fruits", "pronunciation" => "shuǐ guǒ", "chapter" => "7", "new" => "yes"},
  {"front" => "现在", "back" => "now", "pronunciation" => "xiàn zài", "chapter" => "7", "new" => "yes"},
  {"front" => "开会", "back" => "to attend a meeting", "pronunciation" => "kāi huì", "chapter" => "7", "new" => "yes"},
  {"front" => "时侯", "back" => "time", "pronunciation" => "shí hòu", "chapter" => "7", "new" => "yes"},
  {"front" => "开始", "back" => "to start", "pronunciation" => "kāi shǐ", "chapter" => "7", "new" => "yes"},
  {"front" => "下午", "back" => "afternoon", "pronunciation" => "xià wǔ", "chapter" => "7", "new" => "yes"},
  {"front" => "那么", "back" => "then", "pronunciation" => "nà me", "chapter" => "7", "new" => "yes"},
  {"front" => "再见", "back" => "goodbye", "pronunciation" => "zài jiàn", "chapter" => "7", "new" => "yes"},
  {"front" => "办公室", "back" => "office", "pronunciation" => "bàn gōng shì", "chapter" => "7", "new" => "yes"},
  {"front" => "请问，现在几点？", "back" => "excuse me what time is it now?", "pronunciation" => "qǐng wèn, xiàn zài jǐ diǎn?", "chapter" => "7", "new" => "yes"},
  {"front" => "一点差无分", "back" => "Five to one", "pronunciation" => "yì diǎn chà wǔ fēn", "chapter" => "7", "new" => "yes"},
  {"front" => "你有什么急事？", "back" => "Do you have an urgent matter?", "pronunciation" => "nǐ yǒu shén me jí shì", "chapter" => "7", "new" => "yes"},
  {"front" => "我要去大学开会", "back" => "I must go to the university for a meeting.", "pronunciation" => "wǒ yào gù dà xué kāi huì", "chapter" => "7", "new" => "yes"},
  {"front" => "会什么时侯开始？", "back" => "At what time does the meeting start?", "pronunciation" => "huì shén me shí hòu kāi shǐ", "chapter" => "7", "new" => "yes"},
  {"front" => "下午两点半", "back" => "2:30 pm", "pronunciation" => "xià wǔ liǎng diǎn bàn", "chapter" => "7", "new" => "yes"},
  {"front" => "现在才一点，还早呢", "back" => "It's just one o'clock now. It is still early.", "pronunciation" => "xiàn zài cái yì diǎn, hái zǎo ne", "chapter" => "7", "new" => "yes"},
  {"front" => "这几天，我身体不好", "back" => "These few days, I'm not feeling well.", "pronunciation" => "zhè jǐ tiān, wǒ shēn tǐ bú hǎo", "chapter" => "7", "new" => "yes"},
  {"front" => "我想先去办公室休息一下", "back" => "I'd like to go to the office and have a rest first.", "pronunciation" => "wǒ xiǎng xiān gù bàn gōng shì xiū xi yí xià", "chapter" => "7", "new" => "yes"},
  {"front" => "那么再见", "back" => "Then, goodbye", "pronunciation" => "nà me, zài jiàn", "chapter" => "7", "new" => "yes"},

  #lesson 8
  {"front" => "言", "back" => "words", "pronunciation" => "yán", "chapter" => "8", "new" => "yes"},
  {"front" => "信", "back" => "letter", "pronunciation" => "xìn", "chapter" => "8", "new" => "yes"},
  {"front" => "计", "back" => "plan", "pronunciation" => "jì", "chapter" => "8", "new" => "yes"},
  {"front" => "舌", "back" => "tongue", "pronunciation" => "shé", "chapter" => "8", "new" => "yes"},
  {"front" => "话", "back" => "talk", "pronunciation" => "huà", "chapter" => "8", "new" => "yes"},
  {"front" => "兑", "back" => "exchange", "pronunciation" => "duì", "chapter" => "8", "new" => "yes"},
  {"front" => "说", "back" => "speak", "pronunciation" => "shuō", "chapter" => "8", "new" => "yes"},
  {"front" => "谢", "back" => "thank", "pronunciation" => "xiè", "chapter" => "8", "new" => "yes"},
  {"front" => "课", "back" => "class", "pronunciation" => "kè", "chapter" => "8", "new" => "yes"},
  {"front" => "进", "back" => "to come in", "pronunciation" => "jìn", "chapter" => "8", "new" => "yes"},
  {"front" => "喝", "back" => "to drink", "pronunciation" => "hē", "chapter" => "8", "new" => "yes"},
  {"front" => "茶", "back" => "tea", "pronunciation" => "chá", "chapter" => "8", "new" => "yes"},
  {"front" => "糖", "back" => "sugar", "pronunciation" => "táng", "chapter" => "8", "new" => "yes"},
  {"front" => "做", "back" => "to do", "pronunciation" => "zuò", "chapter" => "8", "new" => "yes"},
  {"front" => "写", "back" => "to write", "pronunciation" => "xiè", "chapter" => "8", "new" => "yes"},
  {"front" => "快", "back" => "quick, soon", "pronunciation" => "kuài", "chapter" => "8", "new" => "yes"},
  {"front" => "对", "back" => "right, yes", "pronunciation" => "duì", "chapter" => "8", "new" => "yes"},
  {"front" => "方言", "back" => "dialect", "pronunciation" => "fāng yán", "chapter" => "8", "new" => "yes"},
  {"front" => "信心", "back" => "confidence", "pronunciation" => "xìn xīn", "chapter" => "8", "new" => "yes"},
  {"front" => "写信", "back" => "write letters", "pronunciation" => "xiè xìn", "chapter" => "8", "new" => "yes"},
  {"front" => "小说", "back" => "novel", "pronunciation" => "xiǎo shuō", "chapter" => "8", "new" => "yes"},
  {"front" => "说明", "back" => "explain", "pronunciation" => "shuō míng", "chapter" => "8", "new" => "yes"},
  {"front" => "说话", "back" => "to speak", "pronunciation" => "shuō huà", "chapter" => "8", "new" => "yes"},
  {"front" => "硕大话", "back" => "talk big, boast", "pronunciation" => "shuō dà huà", "chapter" => "8", "new" => "yes"},
  {"front" => "上课", "back" => "go to class", "pronunciation" => "shàng kè", "chapter" => "8", "new" => "yes"},
  {"front" => "下课", "back" => "class over", "pronunciation" => "xià kè", "chapter" => "8", "new" => "yes"},
  {"front" => "尺寸", "back" => "size", "pronunciation" => "chǐ cùn", "chapter" => "8", "new" => "yes"},
  {"front" => "计划", "back" => "a plan", "pronunciation" => "jì huà", "chapter" => "8", "new" => "yes"},
  {"front" => "不谢", "back" => "don't mention it", "pronunciation" => "bú xiè", "chapter" => "8", "new" => "yes"},
  {"front" => "工作", "back" => "to work, work", "pronunciation" => "gōng zuò", "chapter" => "8", "new" => "yes"},
  {"front" => "咖啡", "back" => "coffee", "pronunciation" => "kā fēi", "chapter" => "8", "new" => "yes"},
  {"front" => "还是", "back" => "or", "pronunciation" => "hái shì", "chapter" => "8", "new" => "yes"},
  {"front" => "牛奶", "back" => "milk", "pronunciation" => "niú nǎi", "chapter" => "8", "new" => "yes"},
  {"front" => "老师", "back" => "teacher", "pronunciation" => "lǎo shī", "chapter" => "8", "new" => "yes"},
  {"front" => "地方", "back" => "district, province, area", "pronunciation" => "dì fāng", "chapter" => "8", "new" => "yes"},
  {"front" => "学习", "back" => "to study", "pronunciation" => "xué xí", "chapter" => "8", "new" => "yes"},
  {"front" => "一点儿", "back" => "a little bit", "pronunciation" => "yì diǎn ér", "chapter" => "8", "new" => "yes"},
  {"front" => "第一颗", "back" => "first lesson", "pronunciation" => "dè yi1 kè", "chapter" => "8", "new" => "yes"},
  {"front" => "对不起", "back" => "sorry", "pronunciation" => "duì bu qǐ", "chapter" => "8", "new" => "yes"},
  {"front" => "请问，李小姐在家吗？", "back" => "Excuse me, is Miss Li at home?", "pronunciation" => "qǐng wèn, lǐ xiǎo jiě zài jiā ma?", "chapter" => "8", "new" => "yes"},
  {"front" => "你好，马先生", "back" => "How do you do, Mr Ma.", "pronunciation" => "nǐ hǎo, mǎ xiān sheng", "chapter" => "8", "new" => "yes"},
  {"front" => "请进。请坐", "back" => "Please come in and sit down.", "pronunciation" => "qǐng jìn. qǐng zuò", "chapter" => "8", "new" => "yes"},
  {"front" => "你想喝什么咖啡还是茶", "back" => "What would you like to drink, coffee or tea?", "pronunciation" => "nǐ xiǎng hē shén me, kā fēi hái shì chá?", "chapter" => "8", "new" => "yes"},
  {"front" => "我喝茶，不要牛奶和糖", "back" => "Tea with no milk and sugar.", "pronunciation" => "wǒ hē chà, bú yào niú nǎi hé táng", "chapter" => "8", "new" => "yes"},
  {"front" => "你在什么地方工作", "back" => "Where do you work?", "pronunciation" => "nǐ zài shén me dì fāng gōng zuò", "chapter" => "8", "new" => "yes"},
  {"front" => "我在大学工作", "back" => "I work at the university.", "pronunciation" => "wǒ zài dà xué gōng zuò", "chapter" => "8", "new" => "yes"},
  {"front" => "你做什么", "back" => "What do you do?", "pronunciation" => "nǐ zuò shén me", "chapter" => "8", "new" => "yes"},
  {"front" => "我是中文老师", "back" => "I'm a teacher of Chinese", "pronunciation" => "wǒ shì zhōng wén lǎo shī", "chapter" => "8", "new" => "yes"},
  {"front" => "对不起，我不工作", "back" => "I'm sorry, I do not work.", "pronunciation" => "duì bu qǐ, wǒ bù gōng zuò", "chapter" => "8", "new" => "yes"},
  {"front" => "我在大学学习", "back" => "I'm studying at a university.", "pronunciation" => "wǒ zài dà xué xué xí", "chapter" => "8", "new" => "yes"},
  {"front" => "你学什么", "back" => "What do you study?", "pronunciation" => "nǐ xué shén me?", "chapter" => "8", "new" => "yes"},
  {"front" => "我学中文。我会说一点儿中国话", "back" => "I study Chinese. I can speak a little bit of Chinese", "pronunciation" => "wǒ xué zhōng wén. wǒ huì shuō yì diǎn ér zhōng guó huà", "chapter" => "8", "new" => "yes"},
  {"front" => "你会写中文信吗？", "back" => "Can you write a letter in Chinese？", "pronunciation" => "nǐ huì xiè zhōng wén xìn ma?", "chapter" => "8", "new" => "yes"},
  {"front" => "还不会。我有信心我很快会写中文信的", "back" => "Not yet. I have confidence that I will be able to write Chinese letters soon.", "pronunciation" => "hái bú huì. wǒ yǒu xìn xīn wǒ hěn kuài huì xiè zhōng wén xìn de.", "chapter" => "8", "new" => "yes"},
  {"front" => "对，你一定会", "back" => "Yes, you definately will.", "pronunciation" => "duì, nǐ yí dìng huì", "chapter" => "8", "new" => "yes"},

  #lesson 9
  {"front" => "斤", "back" => "500 grams", "pronunciation" => "jīn", "chapter" => "9", "new" => "yes"},
  {"front" => "近", "back" => "near", "pronunciation" => "jìn", "chapter" => "9", "new" => "yes"},
  {"front" => "听", "back" => "listen", "pronunciation" => "tīng", "chapter" => "9", "new" => "yes"},
  {"front" => "匠", "back" => "craftsman", "pronunciation" => "jiàng", "chapter" => "9", "new" => "yes"},
  {"front" => "兵", "back" => "soldier, troops", "pronunciation" => "bīng", "chapter" => "9", "new" => "yes"},
  {"front" => "所", "back" => "place", "pronunciation" => "suǒ", "chapter" => "9", "new" => "yes"},
  {"front" => "新", "back" => "new", "pronunciation" => "xīn", "chapter" => "9", "new" => "yes"},
  {"front" => "质", "back" => "quality", "pronunciation" => "zhì", "chapter" => "9", "new" => "yes"},
  {"front" => "少", "back" => "few, little", "pronunciation" => "shǎo", "chapter" => "9", "new" => "yes"},
  {"front" => "站", "back" => "station, stop", "pronunciation" => "zhàn", "chapter" => "9", "new" => "yes"},
  {"front" => "再", "back" => "again, twice", "pronunciation" => "zài", "chapter" => "9", "new" => "yes"},
  {"front" => "换", "back" => "to change", "pronunciation" => "huàn", "chapter" => "9", "new" => "yes"},
  {"front" => "到", "back" => "to arrive", "pronunciation" => "dào", "chapter" => "9", "new" => "yes"},
  {"front" => "公斤", "back" => "kilogram", "pronunciation" => "gon1 jīn", "chapter" => "9", "new" => "yes"},
  {"front" => "附近", "back" => "nearby", "pronunciation" => "fù jìn", "chapter" => "9", "new" => "yes"},
  {"front" => "听说", "back" => "hearsay, to hear, was told", "pronunciation" => "tīng shuō", "chapter" => "9", "new" => "yes"},
  {"front" => "听见", "back" => "hear", "pronunciation" => "tīng jiàn", "chapter" => "9", "new" => "yes"},
  {"front" => "听话", "back" => "be obedient", "pronunciation" => "tīng huà", "chapter" => "9", "new" => "yes"},
  {"front" => "听众", "back" => "audience", "pronunciation" => "tīng zhòng", "chapter" => "9", "new" => "yes"},
  {"front" => "木匠", "back" => "carpenter", "pronunciation" => "mù jiàng", "chapter" => "9", "new" => "yes"},
  {"front" => "士兵", "back" => "soldier", "pronunciation" => "shì bīng", "chapter" => "9", "new" => "yes"},
  {"front" => "所以", "back" => "so, therefore", "pronunciation" => "suǒ yǐ", "chapter" => "9", "new" => "yes"},
  {"front" => "住所", "back" => "living place (usage)", "pronunciation" => "zhù suǒ", "chapter" => "9", "new" => "yes"},
  {"front" => "厕所", "back" => "toilet", "pronunciation" => "cè suǒ", "chapter" => "9", "new" => "yes"},
  {"front" => "品质", "back" => "quality, character", "pronunciation" => "pǐn zhì", "chapter" => "9", "new" => "yes"},
  {"front" => "怎么", "back" => "how", "pronunciation" => "zěn me", "chapter" => "9", "new" => "yes"},
  {"front" => "开车", "back" => "to drive (a car）", "pronunciation" => "kāi chē", "chapter" => "9", "new" => "yes"},
  {"front" => "坐车", "back" => "to take buses", "pronunciation" => "zuò chē", "chapter" => "9", "new" => "yes"},
  {"front" => "因为", "back" => "because", "pronunciation" => "yīn wèi", "chapter" => "9", "new" => "yes"},
  {"front" => "车位", "back" => "parking space", "pronunciation" => "chē wèi", "chapter" => "9", "new" => "yes"},
  {"front" => "火车", "back" => "train", "pronunciation" => "huǒ chē", "chapter" => "9", "new" => "yes"},
  {"front" => "电车", "back" => "tram", "pronunciation" => "diàn chē", "chapter" => "9", "new" => "yes"},
  {"front" => "下车", "back" => "to get off (a bus）", "pronunciation" => "xià chē", "chapter" => "9", "new" => "yes"},
  {"front" => "多长", "back" => "how long", "pronunciation" => "duō cháng", "chapter" => "9", "new" => "yes"},
  {"front" => "时间", "back" => "time (variation)", "pronunciation" => "shí jiān", "chapter" => "9", "new" => "yes"},
  {"front" => "小时", "back" => "hour xiǎo", "pronunciation" => "shí", "chapter" => "9", "new" => "yes"},
  {"front" => "去墨尔本大学怎么走？", "back" => "How to go to Melbourne University?", "pronunciation" => "gù mò er běn dà xué zěn me zǒu?", "chapter" => "9", "new" => "yes"},
  {"front" => "你开车去还是坐车去", "back" => "Do you drive or take buses?", "pronunciation" => "nǐ kāi chē gù hái shì zuò chē gù?", "chapter" => "9", "new" => "yes"},
  {"front" => "我坐车去，因为大学里车位很少", "back" => "I go by bus, because in the university parking spaces are few.", "pronunciation" => "wǒ zuò chē gù, yīn wèi dà xué lǐ chē wèi hěn shǎo.", "chapter" => "9", "new" => "yes"},
  {"front" => "附近有个新火车站", "back" => "Nearby, there is a new train station", "pronunciation" => "fù jìn yǒu gé xīn huǒ chē zhàn.", "chapter" => "9", "new" => "yes"},
  {"front" => "你可以先坐火车，再换电车在大学下车", "back" => "You can first take a train, then change to a tram and get off at the University.", "pronunciation" => "nǐ kě yǐ xiān zuò huǒ chē zài huàn diàn chē, zài dà xué xià chē.", "chapter" => "9", "new" => "yes"},
  {"front" => "多长时间可以到？", "back" => "How long does it take?", "pronunciation" => "duō cháng shí jiān kě yǐ dào?", "chapter" => "9", "new" => "yes"},
  {"front" => "听说一个小时左右", "back" => "From hearsay one hour approximately.", "pronunciation" => "tīng shuō yí gé xiǎo shí zuǒ yòu", "chapter" => "9", "new" => "yes"},

  #lesson 10
  {"front" => "忙", "back" => "busy", "pronunciation" => "máng", "chapter" => "10", "new" => "yes"},
  {"front" => "祝", "back" => "to wish", "pronunciation" => "zhù", "chapter" => "10", "new" => "yes"},
  {"front" => "爸爸", "back" => "father", "pronunciation" => "bà ba", "chapter" => "10", "new" => "yes"},
  {"front" => "每天", "back" => "everyday (variation)", "pronunciation" => "měi tiān", "chapter" => "10", "new" => "yes"},
  {"front" => "没有", "back" => "have not", "pronunciation" => "méi yǒu", "chapter" => "10", "new" => "yes"},
  {"front" => "快乐", "back" => "happy", "pronunciation" => "kuài lè", "chapter" => "10", "new" => "yes"}
  ]

#āáǎàa
#ēéěèe
#īíǐìi
#ōóǒòo
#ūúǔùuǚ

add_cards_to_forward_deck forward_deck, cards
add_cards_to_reverse_deck reverse_deck, cards
add_cards_to_reverse_deck typing_deck, cards