#UploadDictionaryJob.new("spanish", "en-es-a").check
#UploadDictionaryJob.new("spanish", "en-es-b").check
#UploadDictionaryJob.new("spanish", "en-es-c").check
#UploadDictionaryJob.new("spanish", "en-es-d").check
#UploadDictionaryJob.new("spanish", "en-es-e").check
#UploadDictionaryJob.new("spanish", "en-es-f").check
#UploadDictionaryJob.new("spanish", "en-es-g").check
#UploadDictionaryJob.new("spanish", "en-es-h").check
#UploadDictionaryJob.new("spanish", "en-es-i").check
#UploadDictionaryJob.new("spanish", "en-es-j").check
#UploadDictionaryJob.new("spanish", "en-es-k").check
#UploadDictionaryJob.new("spanish", "en-es-l").check
#UploadDictionaryJob.new("spanish", "en-es-m").check
#UploadDictionaryJob.new("spanish", "en-es-n").check
#UploadDictionaryJob.new("spanish", "en-es-o").check
#UploadDictionaryJob.new("spanish", "en-es-p").check
#UploadDictionaryJob.new("spanish", "en-es-q").check
#UploadDictionaryJob.new("spanish", "en-es-r").check
#UploadDictionaryJob.new("spanish", "en-es-s").check
#UploadDictionaryJob.new("spanish", "en-es-t").check
#UploadDictionaryJob.new("spanish", "en-es-u").check
#UploadDictionaryJob.new("spanish", "en-es-v").check
#UploadDictionaryJob.new("spanish", "en-es-w").check
#UploadDictionaryJob.new("spanish", "en-es-x").check
#UploadDictionaryJob.new("spanish", "en-es-y").check
#UploadDictionaryJob.new("spanish", "en-es-z").check
#UploadDictionaryJob.new("spanish", "en-es-0").check

#UploadDictionaryJob.new("french", "en-fr-a").check
#UploadDictionaryJob.new("french", "en-fr-b").check
#UploadDictionaryJob.new("french", "en-fr-c").check
#UploadDictionaryJob.new("french", "en-fr-d").check
#UploadDictionaryJob.new("french", "en-fr-e").check
#UploadDictionaryJob.new("french", "en-fr-f").check
#UploadDictionaryJob.new("french", "en-fr-g").check
#UploadDictionaryJob.new("french", "en-fr-h").check
#UploadDictionaryJob.new("french", "en-fr-i").check
#UploadDictionaryJob.new("french", "en-fr-j").check
#UploadDictionaryJob.new("french", "en-fr-k").check
#UploadDictionaryJob.new("french", "en-fr-l").check
#UploadDictionaryJob.new("french", "en-fr-m").check
#UploadDictionaryJob.new("french", "en-fr-n").check
#UploadDictionaryJob.new("french", "en-fr-o").check
#UploadDictionaryJob.new("french", "en-fr-p").check
#UploadDictionaryJob.new("french", "en-fr-q").check
#UploadDictionaryJob.new("french", "en-fr-r").check
#UploadDictionaryJob.new("french", "en-fr-s").check
#UploadDictionaryJob.new("french", "en-fr-t").check
#UploadDictionaryJob.new("french", "en-fr-u").check
#UploadDictionaryJob.new("french", "en-fr-v").check
#UploadDictionaryJob.new("french", "en-fr-w").check
#UploadDictionaryJob.new("french", "en-fr-x").check
#UploadDictionaryJob.new("french", "en-fr-y").check
#UploadDictionaryJob.new("french", "en-fr-z").check
#UploadDictionaryJob.new("french", "en-fr-0").check